/**
 * Builds every package output into dist/:
 *
 *   dist/svelte/   Svelte 5 source and pure modules (svelte-package)
 *   dist/index.js  ESM entry that registers the elements (vite.esm.config.ts)
 *   dist/cdn/v1.js classic script that registers the elements (vite.cdn.config.ts)
 *   dist/jsx/      React, Preact and Solid JSX typings
 *   dist/index.d.ts types for the ESM entry, pointing into dist/svelte
 */
import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';

/** @param {string} command @param {string[]} args */
const run = (command, args) => execFileSync(command, args, { stdio: 'inherit' });

rmSync('dist', { recursive: true, force: true });

// Svelte source entry. svelte-package copies every file under src/lib, so the
// tests and the test-only files are removed from its output afterwards.
run('svelte-package', ['--input', 'src/lib', '--output', 'dist/svelte']);
rmSync('dist/svelte/__tests__', { recursive: true, force: true });

// The two custom-element builds. The CDN build empties its own folder only.
run('vite', ['build', '--config', 'vite.esm.config.ts', '--logLevel', 'warn']);
run('vite', ['build', '--config', 'vite.cdn.config.ts']);

// Types for the ESM entry. src/index.ts re-exports from src/lib, and
// svelte-package has already emitted declarations for those files.
writeFileSync(
	'dist/index.d.ts',
	[
		'// Generated by scripts/build.mjs. Types for src/index.ts.',
		"export * from './svelte/modules.js';",
		"export type { ShowfmPlayerAttributes, ShowfmPlayerElement } from './svelte/element-types.js';",
		''
	].join('\n')
);

// JSX typings: type-only entries, each with an empty module beside it so the
// export resolves for runtimes as well as for TypeScript.
mkdirSync('dist/jsx', { recursive: true });
for (const file of readdirSync('src/jsx')) {
	if (!file.endsWith('.d.ts')) continue;
	cpSync(`src/jsx/${file}`, `dist/jsx/${file}`);
	writeFileSync(`dist/jsx/${file.replace(/\.d\.ts$/, '.js')}`, 'export {};\n');
}
