/**
 * Builds every package output into dist/:
 *
 *   dist/svelte/    Svelte 5 source and pure modules (svelte-package)
 *   dist/cdn/v1.js  classic script that registers the elements (vite.cdn.config.ts)
 *   dist/cdn/click-loader.js  the inline load="click" loader (vite.loader.config.ts)
 *   dist/cdn/v1-fallback.css  optional styles for elements before they upgrade
 *   dist/server.js  the pure modules, no side effects (vite.server.config.ts)
 *   dist/index.js   the package root: dist/server.js plus the registration
 *   dist/jsx/       React, Preact and Solid JSX typings
 *   dist/*.d.ts     types for the root and server entries, pointing into dist/svelte
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { transformWithEsbuild } from 'vite';

/** @param {string} command @param {string[]} args */
const run = (command, args) => execFileSync(command, args, { stdio: 'inherit' });

rmSync('dist', { recursive: true, force: true });

// Svelte source entry. svelte-package copies every file under src/lib, so the
// tests are removed from its output afterwards.
run('svelte-package', ['--input', 'src/lib', '--output', 'dist/svelte']);
rmSync('dist/svelte/__tests__', { recursive: true, force: true });

// The classic script (empties dist/cdn only) and the pure server entry.
run('vite', ['build', '--config', 'vite.cdn.config.ts']);
run('vite', ['build', '--config', 'vite.server.config.ts', '--logLevel', 'warn']);
run('vite', ['build', '--config', 'vite.loader.config.ts', '--logLevel', 'warn']);

// The fallback stylesheet, minified.
const fallbackCss = await transformWithEsbuild(
	readFileSync('src/cdn/v1-fallback.css', 'utf-8'),
	'v1-fallback.css',
	{ loader: 'css', minify: true, target: ['chrome87', 'edge88', 'firefox78', 'safari14'] }
);
writeFileSync('dist/cdn/v1-fallback.css', fallbackCss.code);

// The package root. Svelte's compiled element code calls
// customElements.define and extends HTMLElement as soon as it runs, so it
// cannot be imported unguarded in Node or SSR. The root therefore carries
// the classic script verbatim inside a function, and calls it synchronously
// only where custom elements exist. One build of the elements is used
// everywhere, and a browser import still registers before it returns.
const v1 = readFileSync('dist/cdn/v1.js', 'utf-8');
writeFileSync(
	'dist/index.js',
	[
		'// Generated by scripts/build.mjs. Registers the show.fm elements in browsers',
		'// (the body of registerShowfmElements is dist/cdn/v1.js) and re-exports the',
		'// pure modules from ./server.js. Importing it outside a browser is safe.',
		"export * from './server.js';",
		'function registerShowfmElements() {',
		v1.trimEnd(),
		'}',
		"if (typeof customElements !== 'undefined' && typeof HTMLElement !== 'undefined' && !customElements.get('showfm-player')) {",
		'\tregisterShowfmElements();',
		'}',
		''
	].join('\n')
);

// Types for the root and server entries. svelte-package has already emitted
// declarations for src/lib.
writeFileSync(
	'dist/server.d.ts',
	"// Generated by scripts/build.mjs. Types for src/server.ts.\nexport * from './svelte/modules.js';\n"
);
writeFileSync(
	'dist/index.d.ts',
	[
		'// Generated by scripts/build.mjs. Types for the package root.',
		"export * from './server.js';",
		"export type { ShowfmPlayerAttributes, ShowfmPlayerElement } from './svelte/element-types.js';",
		''
	].join('\n')
);

// JSX typings: type-only entries, each with an empty module beside it so the
// export resolves for runtimes as well as for TypeScript.
mkdirSync('dist/jsx', { recursive: true });
for (const file of readdirSync('src/jsx')) {
	if (!file.endsWith('.d.ts')) continue;
	// src/lib is shipped as dist/svelte, so the one relative import moves with it.
	const source = readFileSync(`src/jsx/${file}`, 'utf-8');
	writeFileSync(`dist/jsx/${file}`, source.replaceAll("'../lib/", "'../svelte/"));
	writeFileSync(`dist/jsx/${file.replace(/\.d\.ts$/, '.js')}`, 'export {};\n');
}
